AllCops:
  Exclude:
    - db/**/*
    - node_modules/**/*
    - vendor/**/*
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Max: 4
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Max: 175
Metrics/MethodLength:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false