language: ruby
rvm:
  - 2.2.0
env:
  - DB=sqlite
script:
  - bundle exec rspec
before_script:
  - cp config/database.travis.yml config/database.yml
  - npm install -g bower
  - redis-server --daemonize yes
  - bundle exec sidekiq -d
  - bundle exec rake bower:install